version: "3.7"

# Create the network
#   docker network create blog_portfolio_dev_network
# To start the service with the environment variable
#   docker compose --env-file ./docker/dev/.env.dev -f ./docker/dev/compose.dev.yaml up

services:
  database:
    container_name: postgres_database
    image: postgres:latest
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./evn_data/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - blog_portfolio_dev_network
    healthcheck:
      test: pg_isready && echo "PostgreSQL is running" || echo "PostgreSQL is not running"

  cache:
    container_name: redis_cache
    image: redis:latest
    networks:
      - blog_portfolio_dev_network

  reverse_proxy:
    container_name: nginx_proxy
    image: nginx:latest
    networks:
      - blog_portfolio_dev_network

  backend:
    container_name: directus_backend_app
    image: directus/directus:latest
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    ports:
      - "8055:8055"
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_STORE: ${CACHE_STORE}
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./evn_data/database:/directus/database
      - ./evn_data/uploads:/directus/uploads
      - ./evn_data/extensions:/directus/extensions
    networks:
      - blog_portfolio_dev_network

  frontend:
    container_name: nextjs_frontend_app
    depends_on:
      - backend
    build:
      context: ../../portfolio-blog-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./evn_data/next-app/src:/app/src
      - ./evn_data/next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - blog_portfolio_dev_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  blog_portfolio_dev_network:
    external: true
