const CurrentTechStack = [
  { key: 1, title: "Java", icon: "work", iconClass: "h-4 w-4" },
  { key: 2, title: "JavaScript", icon: "work", iconClass: "h-4 w-4" },
  { key: 3, title: "Perl", icon: "work", iconClass: "h-4 w-4" },
  { key: 4, title: "Python", icon: "work", iconClass: "h-4 w-4" },
  { key: 5, title: "Go", icon: "work", iconClass: "h-4 w-4" },
  { key: 6, title: "SQL", icon: "work", iconClass: "h-4 w-4" },
  { key: 7, title: "MongoDb", icon: "work", iconClass: "h-4 w-4" },
  { key: 8, title: "Spring Boot", icon: "work", iconClass: "h-4 w-4" },
  { key: 9, title: "Spring", icon: "work", iconClass: "h-4 w-4" },
  { key: 10, title: "ReactJs", icon: "work", iconClass: "h-4 w-4" },
  { key: 11, title: "NextJs", icon: "work", iconClass: "h-4 w-4" },
  { key: 12, title: "Docker", icon: "work", iconClass: "h-4 w-4" },
  { key: 13, title: "Jenkins", icon: "work", iconClass: "h-4 w-4" },
  { key: 14, title: "Keras", icon: "work", iconClass: "h-4 w-4" },
  { key: 15, title: "Linux", icon: "work", iconClass: "h-4 w-4" },
  { key: 16, title: "Git", icon: "work", iconClass: "h-4 w-4" },
  { key: 17, title: "Maven", icon: "work", iconClass: "h-4 w-4" },
  { key: 18, title: "Gradle", icon: "work", iconClass: "h-4 w-4" },
  { key: 19, title: "cMake", icon: "work", iconClass: "h-4 w-4" },
  { key: 20, title: "Redis", icon: "work", iconClass: "h-4 w-4" },
  { key: 21, title: "Tailwind", icon: "work", iconClass: "h-4 w-4" },
];
export default CurrentTechStack;
