const siteMetadata = {
  title: "VIKI",
  author: "Vikramaditya Singh",
  designation: "Software engineer",
  headerTitle: "VIKI",
  description: "A posts created with Next.js and Tailwind.css",
  language: "en-us",
  theme: "system", // system, dark or light
  siteUrl: "",
  siteRepo: "",
  siteLogo: "/static/images/logo.png",
  image: "/static/images/logo.png",
  socialBanner: "/static/images/twitter-card.jpg",
  email: "vikramaditya.bhadoria@gmail.com",
  github: "https://github.com/Vikramadtya",
  twitter: "https://twitter.com/Twitter",
  facebook: "https://facebook.com",
  youtube: "https://youtube.com",
  linkedin: "https://www.linkedin.com/in/vikrmadityasngh/",
  instagram: "https://www.instagram.com/blissfullvibes101",
  locale: "en-US",
  analyticsURL: "https://eu.umami.is/share/kzVVpxmlV8WbabaH/something.com",
  postDateTemplate: {
    year: "numeric",
    month: "long",
    day: "numeric",
  },
  blogLink: "https://www.vikramaditya-singh.in",
  openToWork: true,
  giscus: {
    label: "comments",
    commentsRepo: "Vikramadtya/Blog-Scratch",
    commentsRepoId: "R_kgDOLhesvg",
    commentsMapping: "pathname",
    gitHubDiscussionCategory: "Announcements",
    gitHubDiscussionCategoryId: "DIC_kwDOLhesvs4CeB2W",
    emitMetadata: "0",
    strict: "0",
    lightTheme: "noborder_light",
    darkTheme: "noborder_dark",
    reactionsEnabled: "1",
    inputPosition: "top",
    lang: "en",
    loading: "lazy",
  },
};

export default siteMetadata;
