import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css";
import Footer from "@/components/molecules/footer";
import Header from "@/components/molecules/header";
import ThemeProvider from "@/components/utils/themeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="favicon-16x16.png"
        />
        <link rel="manifest" href="site.webmanifest" />
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#1abc9c" />
        <meta name="apple-mobile-web-app-title" content="Portfolio" />
        <meta name="application-name" content="Portfolio" />
        <meta name="msapplication-TileColor" content="#1abc9c" />
        <meta name="theme-color" content="#ecf0f1" />
        <script
          defer
          src="https://eu.umami.is/script.js"
          data-website-id="dffddd2d-5cad-4d0e-8d02-5938a359c24a"
        ></script>
      </head>
      <body className={inter.className}>
        <div className="flex h-screen flex-col justify-between">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="mb-auto">{children}</main>
            <Footer />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
